@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


"E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\common\bin\cspybat" "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\bin\armproc.dll" "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\bin\armstlink.dll"  %1 --plugin "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\bin\armbat.dll" --macro "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\config\debugger\ST\Trace_STM32F3xx.dmac" --flash_loader "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\config\flashloader\ST\FlashSTM32F3xxC.board" --backend -B "--endian=little" "--cpu=Cortex-M4" "--fpu=VFPv4" "-p" "E:\Program Files (x86)\IAR Systems\Embedded Workbench 6.4 Kickstart\arm\CONFIG\debugger\ST\STM32F303xC.ddf" "--semihosting" "--device=STM32F303xC" "--stlink_interface=SWD" "--stlink_reset_strategy=0,2" "--drv_swo_clock_setup=72000000,0,2000000" 


